### ISSUE TITLE
yo polymer not working with node v4.4.3

### ISSUE THREAD

**Issue by cherukumilli** [yeoman/generator-polymer#274]
When I run **yo polymer** in a node v4.4.3 environment, I see the following **Error: Cannot find module 'grouped-queue'** error. Please see full error details below.

btw: ```yo polymer``` works without any errors in *node v0.12.7*

```
$ yo polymer
module.js:327
    throw err;
    ^

Error: Cannot find module 'grouped-queue'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/biz/projects/node_modules/generator-polymer/node_modules/yeoman-generator/node_modules/yeoman-environment/lib/environment.js:8:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by cherukumilli** [comment]
I upgraded node to ```v6.0.0```
```yo polymer``` is working now
